{% set name = "jupyterlab-flake8" %}
{% set version = "0.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jupyterlab_flake8-{{ version }}.tar.gz
  sha256: 952af03d0a7361325b9829ddbb86265c1bed645406093f5a1b9baf5058e0311c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - jupyter_packaging >=0.10,<2
    - jupyterlab >=3.1,<4.dev0
    - pip
  run:
    - python >=3.6

test:
  imports:
    - jupyterlab_flake8
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mlshapiro/jupyterlab-flake8
  summary: jupyterlab extension to lint python code in the notebook and text editor
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rpanai
